
#line 3 "lex.yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	(yytext_ptr) -= (yy_more_len); \
	yyleng = (int) (yy_cp - (yytext_ptr)); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 26
#define YY_END_OF_BUFFER 27
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_acclist[222] =
    {   0,
       27,   26,   22,   26,   25,   26,   21,   26,   17,   21,
       26,   23,   26,   21,   26,   26,   26,   26,   26,   26,
       26,   26,   26,   26,   26,   26,   25,   26,    4,   26,
       23,   26,   26,   26,   26,   26,   26,   26,   26,   26,
       26,   26,   23,   26,   11,   26,   26,16396,   26,16396,
       26,16396,   26,16396,   26,16396,   26,16396,   26,16396,
       26,16396,   26,16396,   26,16396,   17,   19,    2,    4,
        3,16399,   11,16396,   16,16396,16396,16396,16396,16396,
    16396,16396,16396,16396,16396,16396,16396,16396,16396,   19,
       24,    3,    3,    3,    3,    3,    3,    3,    3,    3,

        3,16399, 8207,16399,16396,    8,   24,16396,16396,16396,
    16396,16396,16396,16396,16396,16396,16396,16396,16396,16396,
       20,    1,    3,    3,    3,    3,    3,    3,    3,    3,
        3,    3,16399,16396, 8204,   24,    8,    8,   14,16396,
    16396,16396,16396,16396,16396,16396,16396,16396,16396,16396,
    16396,16396,16396,16396,    3,    3,    3,    3,    3,    3,
        3,    3,    3,    3,    3,    3, 8204, 8204,   14,   14,
     8204,16396, 8205,16393,16394,16397,16396,16396,16396,16396,
       18,   18,    3,    3,    3,    3,    3,   18,    6,16394,
     8205,16393, 8201, 8205, 8205,16393,16394,16397,16393,   18,

    16396,16396,    3,    3, 8205, 8201, 8205,16393,16394,16397,
    16396,16396, 8202,    7,16396,16396,16396,16396,16396,    5,
    16396
    } ;

static const flex_int16_t yy_accept[378] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    3,    5,    7,    9,   12,   14,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       29,   31,   33,   34,   35,   36,   37,   38,   39,   40,
       41,   42,   43,   45,   47,   49,   51,   53,   55,   57,
       59,   61,   63,   65,   67,   68,   68,   69,   69,   69,
       69,   69,   69,   69,   69,   69,   69,   69,   69,   69,
       69,   70,   70,   70,   70,   71,   71,   71,   71,   71,
       71,   71,   71,   71,   71,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   73,   74,   75,
       76,   76,   77,   78,   79,   80,   81,   82,   83,   84,
       85,   86,   87,   88,   89,   90,   90,   90,   91,   91,
       91,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       92,   92,   92,   92,   92,   92,   92,   92,   92,   92,
       93,   94,   95,   96,   97,   98,   99,  100,  101,  102,
      102,  102,  102,  102,  102,  102,  102,  102,  102,  102,
      102,  102,  102,  102,  102,  102,  102,  103,  104,  105,
      106,  106,  107,  108,  108,  109,  109,  109,  110,  111,
      112,  112,  113,  114,  115,  116,  117,  118,  119,  120,

      121,  122,  122,  122,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  123,  123,  123,  123,  123,  123,
      123,  123,  123,  123,  124,  125,  126,  127,  128,  129,
      130,  131,  132,  132,  132,  132,  132,  132,  132,  132,
      132,  132,  132,  133,  133,  133,  133,  133,  133,  133,
      133,  133,  133,  133,  134,  135,  137,  138,  139,  139,
      139,  139,  140,  140,  141,  141,  142,  143,  144,  145,
      146,  147,  148,  149,  150,  151,  152,  153,  154,  155,
      155,  155,  155,  155,  155,  155,  155,  155,  155,  156,
      157,  158,  159,  160,  161,  162,  163,  163,  163,  164,

      164,  164,  164,  165,  166,  167,  167,  167,  168,  169,
      170,  171,  172,  172,  172,  173,  177,  178,  179,  180,
      181,  182,  183,  183,  183,  184,  185,  186,  187,  187,
      187,  188,  189,  189,  190,  190,  190,  191,  192,  193,
      195,  195,  199,  200,  202,  203,  204,  205,  205,  205,
      206,  207,  207,  207,  211,  212,  213,  213,  213,  214,
      215,  216,  216,  216,  216,  217,  217,  217,  218,  218,
      218,  219,  219,  220,  221,  222,  222
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    2,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    3,    4,    4,    5,    4,    6,    6,    4,    7,
        8,    9,   10,   11,   10,    4,   12,   13,   13,   13,
       13,   13,   13,   13,   13,   13,   13,    4,   14,   15,
       16,   15,    4,    4,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       17,   17,   17,   17,   17,   17,   17,   17,   17,   17,
       18,    1,   19,    6,   17,    1,   20,   21,   22,   23,

       24,   25,   26,   27,   28,   17,   17,   29,   17,   30,
       31,   32,   17,   33,   34,   35,   36,   37,   38,   17,
       17,   17,   39,    4,    4,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[40] =
    {   0,
        1,    2,    3,    1,    1,    4,    5,    6,    4,    4,
        7,    4,    8,    9,   10,   11,   12,   13,    1,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   12,   12,
       12,   12,   12,   12,   12,   12,   12,   12,   14
    } ;

static const flex_int16_t yy_base[402] =
    {   0,
        0,    0,   18,   34,   71,    0,  110,    0,  149,    0,
     1129, 1173, 1173, 1173, 1173,    0, 1173,   33,  186,  200,
       17,   22,   23,   27,   33,   37,  163,  225,  239,  270,
     1120,  306,  341,  189,  357,  173,   40,  184,  174,  166,
      190,  188,  210,  209,  382,  398,  193,  223,  213,  198,
      206,  199,  229, 1100,    0, 1117,    0,  244,  250, 1092,
     1114,  238,   34,  232,  234,  237,  243,  248,  250,  253,
     1109, 1078,  256,    0, 1102,  423,  302, 1082, 1077, 1078,
     1076, 1071,  258, 1070,  458,    0, 1073, 1067, 1068, 1066,
     1064,  284, 1061, 1064,  305,  295,  289,  287,  247,  300,

      305,  310,  312,  318,  345,  351,  361,  217,  352, 1074,
      494, 1060,  508,  299,  379,  347,  235,  376,  354,  331,
      390,  370,  349,  393,  394, 1077,  378,    0,  420, 1077,
     1173,  309,  372,  382,  525,  401,  402,  397,  404,  410,
      405, 1059, 1039, 1040, 1035, 1039, 1036, 1040, 1037, 1050,
      560,  431, 1033, 1028, 1028, 1026, 1024,  413, 1020, 1030,
     1013, 1016, 1011, 1015, 1009, 1013, 1009,  420,  435,  438,
      595,  417,  437,  441,  443,  432,  496, 1025,  498,  499,
      526,  531,  555,  630,  517,  500,  528,  552,  512,  539,
        0,  530,  478,  644,  546,  547,  427,  542,  549,  496,

     1026,  551,  481, 1028,    0,  529,  557,  560,  564,  565,
      569,  572,  574,  578,  571,  997, 1008, 1007, 1023,  999,
      991,  991,  997,  608,  999,  982,  986,  981,  971,  956,
      956,  951,  945,  956,  953,  600,  946,  938,  940,  945,
      581,  586,  676,    0,  603,  585,  598,  604,  610,  614,
      616,  617,  626,  645,  646,  692,  651,  964,  671,  652,
      704,  686,  963,  705,  696,  662,  682,  722,    0,  695,
      700,  663,  706,  631,  708,  643,  709,  715,  721,  722,
      725,  724,  728,  932,  925,  955,  921,  927,  917,  927,
      927,  938,  914,  905,  907,  913,  892,  883,  913,  880,

      890,  730,  901,  759,  755,  731,  732,  727,  895,  765,
      892,  769,  775,  778,  758,  792,  753,  772,  757,  737,
      878,  869,  877,  877,  870,  861,  860,  869,  822,  799,
      801,  761,  810,  712,  712,  793,  811,  817,  802,  661,
      814,  851,  458,  588,  830,  557,  526,  820,  826,  516,
      399,  797,  332,    0,  868,  808,  835,  844,  313, 1173,
      817,  873,  876,  842,  812,  852,  858,  816,  693,  181,
      855,  873,  870, 1173,  901, 1173,  919,  931,  941,  951,
      962,  972,  985,  999, 1011, 1020, 1030, 1040, 1050, 1060,
      886, 1070, 1081, 1091, 1101, 1112, 1122, 1127, 1139, 1150,

     1160
    } ;

static const flex_int16_t yy_def[402] =
    {   0,
      376,    1,    1,    1,  376,    5,  376,    7,  376,    9,
      376,  376,  376,  376,  376,  377,  376,  376,  378,  378,
       20,   20,   20,   20,   20,   20,   20,  379,  379,  376,
      376,   30,  380,  376,  380,   35,   35,   35,   35,   35,
       35,   35,  381,   20,  382,  382,   46,   46,   46,   46,
       46,   46,   46,   46,  377,  383,  384,  385,  385,   20,
      386,   20,   20,   20,   20,   20,   20,   20,   20,   20,
      376,   29,   29,   30,  376,   30,  376,   76,   76,   76,
       76,   76,   76,   76,  376,   32,   76,   76,   76,   76,
       76,   76,   76,   35,  376,   35,   35,   35,   35,   35,

       35,   35,   35,   35,  381,  381,  381,   20,  385,  376,
      387,   46,  376,   46,   46,   46,   46,   46,   46,   46,
       46,   46,   46,   46,   46,  383,  383,  384,  376,  386,
      376,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       29,   76,   76,   76,   76,   76,   76,   76,   76,  376,
       85,  376,  151,  151,  151,  151,  151,  151,  151,   76,
       76,   76,   76,   76,   76,   76,   76,   35,   35,   35,
       35,   35,   35,   35,   35,   35,  376,  376,  376,  376,
      388,  389,  390,  390,  376,  376,  376,  376,   46,  109,
      391,   46,   46,   46,   46,   46,   46,   46,   46,   46,

      383,   20,   20,   59,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   29,   76,   76,   76,   30,   76,
       76,   76,   76,  376,  151,  151,  151,  151,  151,  151,
      151,  151,   76,   76,   76,   32,   76,   76,   76,   76,
       35,   35,  392,   35,   35,   35,   35,   35,   35,   35,
       35,   35,   35,  376,  376,  393,  389,  257,  376,  184,
      393,  376,  394,  376,  391,   46,   46,  395,   46,   46,
       46,   46,   46,   46,   46,   46,   46,   46,   46,   20,
       20,   20,   29,   76,   76,   76,   76,   76,  151,  151,
      151,   85,  151,  151,  151,  151,   76,   76,  151,   76,

       76,   35,  376,  392,  376,   35,   35,  261,  376,  376,
      376,  394,  376,  396,   46,  395,   46,   46,   46,   46,
       20,   29,   76,   76,  151,  151,  151,  151,   76,   76,
      376,   35,  396,  376,  333,  397,  376,  376,  376,  376,
      376,  376,  376,   46,   46,  151,  151,  397,  397,  376,
      376,  376,  398,  342,  399,   46,  376,  400,  398,  376,
       46,  400,  400,  401,   46,  401,  401,   46,  376,  376,
       46,  376,   46,  376,  399,    0,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376
    } ;

static const flex_int16_t yy_nxt[1213] =
    {   0,
       12,   13,   14,   15,   16,   15,   12,   12,   15,   12,
       17,   18,   19,   15,   15,   15,   19,   12,   12,   19,
       19,   20,   21,   19,   22,   19,   19,   23,   24,   19,
       19,   25,   19,   26,   19,   19,   27,   19,   15,   19,
       19,   56,   19,   60,   57,   19,   19,   63,   60,   60,
       64,   19,   65,   60,   19,   19,   19,   66,   19,   60,
       60,   19,   19,   68,   69,   67,   94,   19,   98,  133,
       19,   12,   13,   14,   15,   16,   15,   12,   12,   15,
       12,   17,   18,   28,   15,   15,   15,   28,   12,   12,
       28,   28,   28,   28,   28,   28,   28,   28,   28,   28,

       28,   28,   29,   28,   28,   28,   28,   28,   28,   15,
       12,   13,   30,   15,   16,   15,   12,   31,   15,   12,
       32,   18,   33,   15,   15,   15,   33,   34,   12,   33,
       33,   35,   36,   33,   37,   33,   33,   38,   39,   33,
       33,   40,   33,   41,   33,   33,   42,   33,   15,   12,
       13,   14,   15,   16,   15,   12,   12,   15,   12,   43,
       18,   44,   15,   15,   15,   45,   12,   12,   45,   45,
       46,   47,   45,   48,   45,   45,   49,   50,   45,   45,
       51,   52,   53,   45,   45,   45,   54,   15,   58,   60,
      372,   59,   94,   70,   59,   59,   75,   59,  101,   94,

       94,   61,   58,   97,  100,   59,   77,   95,   59,   59,
       94,   59,  105,   99,   94,   61,  102,  103,  104,  112,
      106,  108,  122,  115,  112,  112,   62,   58,  120,  108,
       59,   71,  112,   59,   59,   60,   59,  118,  121,  112,
       61,   58,  119,   60,   59,   71,   58,   59,   59,  112,
       59,  116,  129,  117,   61,  123,  124,  132,   60,   61,
       60,  112,  134,   60,   60,   61,  136,  118,  135,   60,
      137,   73,   74,   94,   60,  139,   60,   75,  138,   60,
      140,  171,   76,  141,  147,  148,   76,   77,   72,   76,
       76,   78,   79,   76,   80,   76,   76,   81,   82,   76,

       76,   76,   76,   83,   76,   76,   84,   76,   85,   75,
      165,  166,   75,   94,  168,   94,   86,  170,  189,   77,
       95,   94,   77,   95,  169,  112,   94,   87,   88,  172,
       89,   94,  173,   90,   91,   60,   94,  175,   94,   92,
      174,  135,   93,   58,   94,  176,   59,  105,   75,   59,
       59,  376,   59,  105,  109,  376,   61,  112,   77,   58,
      195,  106,   59,  177,   75,   59,   59,  111,   59,  180,
      353,  178,   61,  112,   77,  112,  179,  193,  190,  198,
      112,  190,  191,   96,  109,  191,  127,   59,  194,  201,
       59,   59,  202,   59,   60,  110,  112,  111,   60,  113,

      109,  203,  112,   59,  197,  112,   59,   59,   60,   59,
       60,  110,  351,  111,  192,  113,  112,  196,  199,  112,
      112,  200,  129,   60,  114,  376,  135,   60,   60,  213,
       60,  212,  135,  214,  215,   61,   60,   72,   75,  230,
      231,  150,  171,   94,   76,   76,   94,   76,  152,  224,
       76,   76,  171,  112,  171,  241,   76,  242,   94,   76,
       85,   94,  276,   94,   94,   75,  251,   94,  150,   94,
      151,  351,  253,  252,  151,  152,  343,  151,  151,  153,
      154,  151,  155,  151,  151,  156,  157,  151,  151,  151,
      151,  158,  151,  151,  159,  151,  181,  267,  177,  182,

      254,  185,  182,  182,  112,  182,  178,   60,  178,  184,
      185,  179,  186,  179,  187,  135,  180,  255,  262,  185,
      186,  110,  112,  187,  279,  113,  188,  204,  181,  350,
      263,  182,  187,  257,  182,  182,  182,  182,  112,  182,
      182,  190,  182,  187,  194,  191,  205,  206,  292,  207,
      266,   60,  208,  209,  185,   60,  112,  259,  210,   63,
      182,  211,  376,  182,  182,  110,  182,  187,  112,  264,
      188,  194,  112,  112,  277,  112,  275,   60,  278,  280,
      292,  151,  151,   60,  151,   64,   60,  151,  151,   65,
       60,   68,   69,  151,   66,   60,  151,  243,   60,   70,

       60,  282,  299,   72,   60,  283,  281,   94,  135,  302,
      376,   94,   94,   98,  112,   75,  244,  245,  150,  246,
      171,   94,  247,  248,   94,  152,  224,   99,  249,   94,
       94,  250,  261,   97,  100,  182,  102,  103,  182,  182,
       94,  182,   94,   94,  104,  184,  268,  254,  185,  307,
      306,  171,   94,  257,  259,  178,  376,  123,  124,  376,
      376,  187,  376,  180,  255,  269,  270,  376,  271,  112,
      112,  272,  273,  259,  340,  319,  182,  274,  243,  182,
      182,   59,  182,   75,   59,   59,  303,   59,  112,  112,
      315,   61,  119,  305,  259,  369,  310,  182,  313,  311,

      182,  182,  370,  182,  262,  309,  261,  185,  112,  182,
      314,  314,  182,  182,  376,  182,  194,  376,  110,  334,
      187,  112,  264,  188,  268,  317,  112,   59,  116,  259,
       59,   59,  112,   59,  112,  112,  120,  111,  320,  180,
      309,  112,  318,  194,  118,  135,  135,  112,   60,  321,
       60,   60,  322,  171,  171,  332,   94,   94,   94,  194,
       72,  376,   75,  112,  376,  303,   75,  376,  376,  303,
      376,  376,  305,  331,  376,  310,  305,  313,  311,  112,
      333,  194,  309,  112,  112,  334,  345,   94,  192,  314,
      314,  336,  314,  314,  337,  348,  344,  376,  112,  352,

      376,  376,  338,  376,  339,  340,  336,  341,   75,  342,
      343,  303,  333,  337,  339,  351,  352,  334,  305,  331,
      343,  236,  348,  336,  376,  376,  341,  338,  357,  341,
      350,  361,  355,  376,  112,  353,  191,  357,  112,  376,
      358,  358,  112,  112,  366,  236,  362,  368,  371,  358,
      358,  365,  353,  337,  366,  364,  112,  364,  358,  358,
      369,  338,  356,  339,  340,  376,  341,  370,  342,  354,
      355,  376,  375,   59,  191,  362,   59,   59,  376,   59,
      374,  112,  372,  111,  373,  180,  364,  376,  376,  364,
      376,  376,  347,  265,  292,  292,  112,  265,  346,  219,

      219,   72,  356,  375,   60,  311,   59,  376,  309,   59,
       59,  303,   59,  330,  236,  299,  111,  236,  180,   55,
      329,   55,   55,   55,   55,   55,   55,   55,   55,   55,
       55,   55,   55,   60,   60,  292,  328,  327,   60,  292,
      299,   60,   60,   72,   72,   72,  326,  325,   72,  292,
      324,   72,   72,   94,   94,  219,   94,  286,   94,  219,
      323,   94,   94,   94,  107,  263,  376,  236,  107,  301,
      300,  236,  298,  107,  112,  112,  297,  236,  296,  112,
      112,  295,  112,  112,  112,  126,  294,  126,  126,  126,
      126,  126,  126,  126,  126,  126,  126,  126,  126,  128,

      293,  128,  128,  128,  128,  128,  128,  128,  128,  128,
      128,  128,  128,   59,   59,  292,  291,  290,  289,  219,
      288,   59,  131,  287,  219,  286,  285,  131,  284,  219,
      204,  131,  183,  183,  127,  178,  240,  183,  239,  238,
      183,  183,  256,  256,  237,  236,  235,  256,  234,  233,
      232,  256,  258,  258,  229,  228,  227,  258,  226,  225,
      150,  258,  260,  260,  223,  222,  221,  260,  220,  219,
      218,  260,  304,  304,  217,  304,  304,  304,  216,  130,
      304,  304,  304,  308,  308,  127,  112,  110,  308,  308,
       94,  167,  308,  312,  164,  163,  162,  161,  312,  160,

      149,  146,  312,  316,  316,  145,  144,  143,  142,   75,
       72,  316,  316,  316,  335,   71,  130,  335,   60,  335,
      335,  335,  335,  335,  349,  127,  125,   75,  376,  349,
      349,  376,  376,  349,  359,  376,  376,  376,  359,  376,
      359,  360,  360,  360,  376,  376,  360,  376,  376,  360,
      360,  360,  363,  376,  376,  376,  376,  363,  363,  363,
      363,  363,  367,  376,  376,  376,  376,  367,  367,  376,
      376,  367,   11,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376
    } ;

static const flex_int16_t yy_chk[1213] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    3,
        3,   18,    3,   21,   18,    3,    3,   21,   22,   23,
       22,    3,   23,   24,    3,    4,    4,   24,    4,   25,
       63,    4,    4,   26,   26,   25,   37,    4,   37,   63,
        4,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    7,
        7,    7,    7,    7,    7,    7,    7,    7,    7,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,    9,    9,
        9,    9,    9,    9,    9,    9,    9,    9,   19,   27,
      370,   19,   40,   27,   19,   19,   34,   19,   40,   36,

       39,   19,   20,   36,   39,   20,   34,   34,   20,   20,
       38,   20,   43,   38,   42,   20,   41,   41,   42,   47,
       43,   44,   52,   47,   50,   52,   20,   28,   50,  108,
       28,   28,   51,   28,   28,   44,   28,   49,   51,   49,
       28,   29,   49,  108,   29,   29,   58,   29,   29,   48,
       29,   48,   59,   48,   29,   53,   53,   62,   64,   58,
       65,  117,   64,   66,   62,   59,   66,  117,   65,   67,
       67,   29,   30,   99,   68,   69,   69,   30,   68,   70,
       70,   99,   30,   73,   83,   83,   30,   30,   73,   30,
       30,   30,   30,   30,   30,   30,   30,   30,   30,   30,

       30,   30,   30,   30,   30,   30,   30,   30,   32,   77,
       92,   92,   95,   98,   96,   97,   32,   98,  114,   77,
       77,   96,   95,   95,   97,  114,  100,   32,   32,  100,
       32,  101,  101,   32,   32,  132,  102,  103,  103,   32,
      102,  132,   32,   33,  104,  104,   33,  105,   33,   33,
       33,  359,   33,  106,  109,  105,   33,  120,   33,   35,
      120,  106,   35,  107,   35,   35,   35,  109,   35,  109,
      353,  107,   35,  116,   35,  123,  107,  116,  118,  123,
      119,  115,  118,   35,   45,  115,  127,   45,  119,  127,
       45,   45,  133,   45,   45,   45,  122,   45,  133,   45,

       46,  134,  118,   46,  122,  115,   46,   46,  134,   46,
       46,   46,  351,   46,  115,   46,  121,  121,  124,  124,
      125,  125,  129,  138,   46,   76,  136,  136,  137,  138,
      139,  137,  140,  139,  141,  129,  140,  141,  152,  158,
      158,  152,  172,  172,   76,   76,  168,   76,  152,  152,
       76,   76,  168,  197,  176,  169,   76,  170,  176,   76,
       85,  169,  197,  173,  170,   85,  173,  174,   85,  175,
       85,  343,  175,  174,   85,   85,  343,   85,   85,   85,
       85,   85,   85,   85,   85,   85,   85,   85,   85,   85,
       85,   85,   85,   85,   85,   85,  111,  193,  177,  111,

      179,  180,  111,  111,  193,  111,  177,  203,  179,  111,
      113,  177,  186,  179,  180,  203,  180,  180,  186,  185,
      113,  113,  200,  113,  200,  113,  113,  135,  181,  350,
      187,  181,  185,  182,  181,  181,  182,  181,  189,  182,
      182,  190,  182,  187,  189,  190,  135,  135,  347,  135,
      192,  135,  135,  135,  188,  206,  192,  183,  135,  206,
      183,  135,  151,  183,  183,  188,  183,  188,  198,  188,
      188,  195,  195,  196,  198,  199,  196,  202,  199,  202,
      346,  151,  151,  207,  151,  207,  208,  151,  151,  208,
      209,  210,  210,  151,  209,  211,  151,  171,  212,  211,

      213,  214,  236,  215,  214,  215,  212,  241,  213,  241,
      236,  246,  242,  246,  344,  224,  171,  171,  224,  171,
      242,  171,  171,  171,  247,  224,  224,  247,  171,  245,
      248,  171,  184,  245,  248,  184,  249,  249,  184,  184,
      250,  184,  251,  252,  250,  184,  194,  254,  255,  253,
      251,  252,  253,  257,  260,  254,  257,  274,  274,  257,
      257,  255,  257,  255,  255,  194,  194,  260,  194,  276,
      194,  194,  194,  259,  340,  276,  259,  194,  243,  259,
      259,  243,  259,  243,  243,  243,  243,  243,  266,  272,
      266,  243,  272,  243,  256,  369,  262,  256,  265,  262,

      256,  256,  369,  256,  262,  256,  261,  264,  267,  261,
      265,  265,  261,  261,  335,  261,  267,  261,  264,  334,
      264,  270,  264,  264,  268,  270,  271,  268,  271,  308,
      268,  268,  273,  268,  275,  277,  273,  268,  278,  268,
      308,  278,  275,  277,  279,  280,  282,  279,  280,  281,
      282,  281,  283,  302,  307,  306,  302,  306,  307,  320,
      283,  304,  305,  320,  304,  305,  304,  304,  304,  304,
      304,  312,  305,  305,  304,  310,  304,  313,  310,  317,
      314,  315,  312,  319,  315,  314,  319,  332,  317,  313,
      313,  314,  314,  314,  316,  336,  318,  316,  318,  352,

      316,  316,  316,  316,  316,  316,  336,  316,  331,  316,
      316,  331,  333,  337,  339,  339,  341,  333,  331,  331,
      339,  330,  348,  333,  333,  333,  337,  338,  349,  341,
      338,  356,  345,  348,  356,  352,  345,  357,  365,  349,
      349,  349,  368,  361,  364,  329,  358,  365,  368,  357,
      357,  361,  341,  342,  366,  364,  345,  358,  358,  358,
      367,  342,  345,  342,  342,  366,  342,  367,  342,  342,
      355,  367,  373,  355,  355,  362,  355,  355,  363,  355,
      372,  371,  372,  355,  371,  355,  362,  362,  362,  363,
      363,  363,  328,  391,  327,  326,  373,  391,  325,  324,

      323,  322,  373,  375,  321,  311,  375,  375,  309,  375,
      375,  303,  375,  301,  300,  299,  375,  298,  375,  377,
      297,  377,  377,  377,  377,  377,  377,  377,  377,  377,
      377,  377,  377,  378,  378,  296,  295,  294,  378,  293,
      292,  378,  378,  379,  379,  379,  291,  290,  379,  289,
      288,  379,  379,  380,  380,  287,  380,  286,  380,  285,
      284,  380,  380,  380,  381,  263,  258,  240,  381,  239,
      238,  237,  235,  381,  382,  382,  234,  233,  232,  382,
      382,  231,  382,  382,  382,  383,  230,  383,  383,  383,
      383,  383,  383,  383,  383,  383,  383,  383,  383,  384,

      229,  384,  384,  384,  384,  384,  384,  384,  384,  384,
      384,  384,  384,  385,  385,  228,  227,  226,  225,  223,
      222,  385,  386,  221,  220,  219,  218,  386,  217,  216,
      204,  386,  387,  387,  201,  178,  167,  387,  166,  165,
      387,  387,  388,  388,  164,  163,  162,  388,  161,  160,
      159,  388,  389,  389,  157,  156,  155,  389,  154,  153,
      150,  389,  390,  390,  149,  148,  147,  390,  146,  145,
      144,  390,  392,  392,  143,  392,  392,  392,  142,  130,
      392,  392,  392,  393,  393,  126,  112,  110,  393,  393,
       94,   93,  393,  394,   91,   90,   89,   88,  394,   87,

       84,   82,  394,  395,  395,   81,   80,   79,   78,   75,
       72,  395,  395,  395,  396,   71,   61,  396,   60,  396,
      396,  396,  396,  396,  397,   56,   54,   31,   11,  397,
      397,    0,    0,  397,  398,    0,    0,    0,  398,    0,
      398,  399,  399,  399,    0,    0,  399,    0,    0,  399,
      399,  399,  400,    0,    0,    0,    0,  400,  400,  400,
      400,  400,  401,    0,    0,    0,    0,  401,  401,    0,
        0,  401,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,

      376,  376,  376,  376,  376,  376,  376,  376,  376,  376,
      376,  376
    } ;

extern int yy_flex_debug;
int yy_flex_debug = 0;

static yy_state_type *yy_state_buf=0, *yy_state_ptr=0;
static char *yy_full_match;
static int yy_lp;
static int yy_looking_for_trail_begin = 0;
static int yy_full_lp;
static int *yy_full_state;
#define YY_TRAILING_MASK 0x2000
#define YY_TRAILING_HEAD_MASK 0x4000
#define REJECT \
{ \
*yy_cp = (yy_hold_char); /* undo effects of setting up yytext */ \
yy_cp = (yy_full_match); /* restore poss. backed-over text */ \
(yy_lp) = (yy_full_lp); /* restore orig. accepting pos. */ \
(yy_state_ptr) = (yy_full_state); /* restore orig. state */ \
yy_current_state = *(yy_state_ptr); /* restore curr. state */ \
++(yy_lp); \
goto find_rule; \
}

static int yy_more_flag = 0;
static int yy_more_len = 0;
#define yymore() ((yy_more_flag) = 1)
#define YY_MORE_ADJ (yy_more_len)
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "tema.l"
#line 3 "tema.l"
#include<stdio.h>
int nr_var_loc = 0;
char* return_type;
char* name_function;
char local_variables[100];
#line 888 "lex.yy.c"

#line 890 "lex.yy.c"

#define INITIAL 0
#define URMATOR 1
#define STARE_1 2
#define STARE_2 3
#define STARE_3 4

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

        /* Create the reject buffer large enough to save one state per allowed character. */
        if ( ! (yy_state_buf) )
            (yy_state_buf) = (yy_state_type *)yyalloc(YY_STATE_BUF_SIZE  );
            if ( ! (yy_state_buf) )
                YY_FATAL_ERROR( "out of dynamic memory in yylex()" );

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 32 "tema.l"


#line 1120 "lex.yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		(yy_more_len) = 0;
		if ( (yy_more_flag) )
			{
			(yy_more_len) = (int) ((yy_c_buf_p) - (yytext_ptr));
			(yy_more_flag) = 0;
			}
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);

		(yy_state_ptr) = (yy_state_buf);
		*(yy_state_ptr)++ = yy_current_state;

yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 377 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			*(yy_state_ptr)++ = yy_current_state;
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1173 );

yy_find_action:
		yy_current_state = *--(yy_state_ptr);
		(yy_lp) = yy_accept[yy_current_state];
find_rule: /* we branch to this label when backing up */
		for ( ; ; ) /* until we find what rule we matched */
			{
			if ( (yy_lp) && (yy_lp) < yy_accept[yy_current_state + 1] )
				{
				yy_act = yy_acclist[(yy_lp)];
				if ( yy_act & YY_TRAILING_HEAD_MASK ||
				     (yy_looking_for_trail_begin) )
					{
					if ( yy_act == (yy_looking_for_trail_begin) )
						{
						(yy_looking_for_trail_begin) = 0;
						yy_act &= ~YY_TRAILING_HEAD_MASK;
						break;
						}
					}
				else if ( yy_act & YY_TRAILING_MASK )
					{
					(yy_looking_for_trail_begin) = yy_act & ~YY_TRAILING_MASK;
					(yy_looking_for_trail_begin) |= YY_TRAILING_HEAD_MASK;
					}
				else
					{
					(yy_full_match) = yy_cp;
					(yy_full_state) = (yy_state_ptr);
					(yy_full_lp) = (yy_lp);
					break;
					}
				++(yy_lp);
				goto find_rule;
				}
			--yy_cp;
			yy_current_state = *--(yy_state_ptr);
			(yy_lp) = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
case 1:
YY_RULE_SETUP
#line 34 "tema.l"
{
	nr_var_loc = 0;
	return_type = malloc(yyleng);
	strcpy(return_type, yytext);
	return_type[yyleng - 1] = '\0';
	yymore();
	BEGIN(STARE_1);
}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 43 "tema.l"
{
	int strlen_name = yyleng - strlen(return_type) - 1;
	name_function = malloc(strlen_name);
	strcpy(name_function, yytext + strlen(return_type) + 1);
	name_function[strlen_name - 1] = '\0';

	yymore();
	BEGIN(STARE_2);
}
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 53 "tema.l"
{
	printf("%s ", yytext);
}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 57 "tema.l"
{
	printf("%s\n", yytext);
	printf("       tip intors: %s\n", return_type);
	printf("       nume: %s\n", name_function);
	BEGIN(STARE_3);
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 64 "tema.l"
;
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 65 "tema.l"
;
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 66 "tema.l"
BEGIN(INITIAL);
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 67 "tema.l"
;
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 69 "tema.l"
{
	printf("       variabile locale: 1 (%s)\n\n", yytext);

	BEGIN(INITIAL);
}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 75 "tema.l"
{
	nr_var_loc++;
	if (strcmp(&yytext[yyleng - 1], " ") == 0) {
		yytext[yyleng - 1] = '\0';
	}
	strcat(local_variables, yytext);
	strcat(local_variables, ", ");
	if (strcmp(&yytext[yyleng - 1], ";") == 0) {
		char new_string[100]; 
		memcpy(new_string, local_variables, strlen(local_variables) - 3);
		memset(local_variables, 0, strlen(local_variables));
		printf("       variabile locale: %d (%s)\n\n", nr_var_loc, new_string);
		nr_var_loc = 0;
		BEGIN(INITIAL);
	}
	BEGIN(STARE_3);
}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 93 "tema.l"
;
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 94 "tema.l"
{
	nr_var_loc++;
	if (strcmp(&yytext[yyleng - 1], " ") == 0) {
		yytext[yyleng - 1] = '\0';
	}
	strcat(local_variables, yytext);
	strcat(local_variables, ", ");
	if (strcmp(&yytext[yyleng - 1], ";") == 0) {
		char new_string[100]; 
		memcpy(new_string, local_variables, strlen(local_variables) - 3);
		memset(local_variables, 0, strlen(local_variables));
		printf("       variabile locale: %d (%s)\n\n", nr_var_loc, new_string);
		nr_var_loc = 0;
		BEGIN(INITIAL);
	}
	BEGIN(STARE_3);
}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 112 "tema.l"
{
	nr_var_loc++;
	strcat(local_variables, yytext);
	strcat(local_variables, ", ");
	if (strcmp(&yytext[yyleng - 1], ";") == 0) {
		char new_string[100]; 
		memcpy(new_string, local_variables, strlen(local_variables) - 3);
		memset(local_variables, 0, strlen(local_variables));
		printf("       variabile locale: %d (%s)\n\n", nr_var_loc, new_string);
		nr_var_loc = 0;
		BEGIN(INITIAL);
	}
	BEGIN(STARE_3);
}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 127 "tema.l"
{
	nr_var_loc++;
	strcat(local_variables, yytext);
	strcat(local_variables, ", ");
		if (strcmp(&yytext[yyleng - 1], ";") == 0) {
		char new_string[100]; 
		memcpy(new_string, local_variables, strlen(local_variables) - 3);
		memset(local_variables, 0, strlen(local_variables));
		printf("       variabile locale: %d (%s)\n\n", nr_var_loc, new_string);
		nr_var_loc = 0;
		BEGIN(INITIAL);
	}
	BEGIN(STARE_3);
}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 142 "tema.l"
{
	nr_var_loc++;
	memcpy(yytext, yytext + 2, strlen(yytext));
	strcat(local_variables, yytext);
	strcat(local_variables, ", ");
	BEGIN(STARE_3);
}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 150 "tema.l"
{
	nr_var_loc++;
	strcat(local_variables, yytext);
	strcat(local_variables, ", ");
	if (strcmp(&yytext[yyleng - 1], ";") == 0) {
		char new_string[100]; 
		memcpy(new_string, local_variables, strlen(local_variables) - 3);
		memset(local_variables, 0, strlen(local_variables));
		printf("       variabile locale: %d (%s)\n\n", nr_var_loc, new_string);
		memset(new_string, 0, strlen(new_string));
		nr_var_loc = 0;
		BEGIN(INITIAL);
	}
	BEGIN(STARE_3);
}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 166 "tema.l"
;
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 167 "tema.l"
;
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 168 "tema.l"
; // comentariu pe o singura linie
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 169 "tema.l"
; // comentariu pe mai multe linii
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 170 "tema.l"
;
	YY_BREAK
case 22:
/* rule 22 can match eol */
YY_RULE_SETUP
#line 171 "tema.l"
;
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 172 "tema.l"
;
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 173 "tema.l"
;
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 174 "tema.l"
;
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 176 "tema.l"
ECHO;
	YY_BREAK
#line 1441 "lex.yy.c"
			case YY_STATE_EOF(INITIAL):
			case YY_STATE_EOF(URMATOR):
			case YY_STATE_EOF(STARE_1):
			case YY_STATE_EOF(STARE_2):
			case YY_STATE_EOF(STARE_3):
				yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	(yy_state_ptr) = (yy_state_buf);
	*(yy_state_ptr)++ = yy_current_state;

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 377 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		*(yy_state_ptr)++ = yy_current_state;
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    
	YY_CHAR yy_c = 1;
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 377 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 376);
	if ( ! yy_is_jam )
		*(yy_state_ptr)++ = yy_current_state;

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_state_buf) = 0;
    (yy_state_ptr) = 0;
    (yy_full_match) = 0;
    (yy_lp) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    yyfree ( (yy_state_buf) );
    (yy_state_buf)  = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 176 "tema.l"


int main(void){
	yyin = fopen("file3.c","r");
	yylex();
	fclose(yyin);
} 
int yywrap(){
	return(1);
}
